In [17]:
import numpy as np
import pandas as pd
arquivo = pd.read_csv('C:/Users/anizio.silva/teste/wine_dataset.csv')
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [18]:
arquivo['style'] = arquivo['style'].replace('red', 0)

In [19]:
arquivo['style'] = arquivo['style'].replace('white', 1)

In [20]:
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [22]:
y = arquivo['style']
x = arquivo.drop('style', axis = 1)
x

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [23]:
arquivo.shape

(6497, 13)

In [40]:
x.shape

(6497, 12)

In [41]:
y.shape

(6497,)

In [28]:
from sklearn.model_selection import train_test_split
 #criando conjuntos de dados de treino e teste, 0.3 é para usar 30% para teste e 30% para treino.
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size = 0.3)

In [30]:
from sklearn.ensemble import ExtraTreesClassifier
#criação do modelo
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

#imprimindo resultado
resultado = modelo.score(x_teste,y_teste)
print("Resultado:", resultado)

Resultado: 0.9953846153846154

In [38]:
y_teste[400:408]

5586    1
1649    1
2617    1
2121    1
4750    1
2710    1
4202    1
4183    1
Name: style, dtype: int64

In [37]:
x_teste[400:408]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
5586,7.3,0.23,0.41,14.6,0.048,73.0,223.0,0.99863,3.16,0.71,9.4,6
1649,7.2,0.19,0.31,1.6,0.062,31.0,173.0,0.99170,3.35,0.44,11.7,6
2617,7.1,0.18,0.42,1.4,0.045,47.0,157.0,0.99160,2.95,0.31,10.5,6
2121,6.9,0.25,0.40,1.3,0.038,22.0,101.0,0.99010,3.03,0.39,11.4,6
4750,6.2,0.23,0.36,17.2,0.039,37.0,130.0,0.99946,3.23,0.43,8.8,6
2710,8.0,0.18,0.37,1.3,0.040,15.0,96.0,0.99120,3.06,0.61,12.1,6
4202,6.7,0.30,0.29,2.8,0.025,37.0,107.0,0.99159,3.31,0.63,11.3,7
4183,6.8,0.18,0.30,12.8,0.062,19.0,171.0,0.99808,3.00,0.52,9.0,7

In [39]:
previsoes = modelo.predict(x_teste[400:408])
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)